# UV Workspace Configuration
[tool.uv.workspace]
members = [
    "atomic-agents",
    "atomic-assembler", 
    "atomic-examples/quickstart",
    "atomic-examples/basic-multimodal",
    "atomic-examples/basic-pdf-analysis",
    "atomic-examples/deep-research",
    "atomic-examples/mcp-agent/example-client",
    "atomic-examples/mcp-agent/example-mcp-server",
    "atomic-examples/orchestration-agent",
    "atomic-examples/rag-chatbot",
    "atomic-examples/web-search-agent",
    "atomic-examples/youtube-summarizer",
    "atomic-examples/youtube-to-recipe",
    "atomic-forge/tools/calculator",
    "atomic-forge/tools/searxng_search"
]

[tool.uv.sources]
atomic-agents = { workspace = true }

[tool.black]
line-length = 127